# Generated by Django 4.0.3 on 2022-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usermailing_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermailing',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
