# Generated by Django 5.1.15 on 2026-03-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_is_liked'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='core_produc_id_799af9_idx',
            old_fields=('id', 'slug'),
        ),
    ]
