# Generated by Django 5.1.15 on 2026-06-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_in", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[("CPU", "CPU"), ("RAM", "RAM"), ("DISK", "DISK")], max_length=4
                    ),
                ),
                ("threshold", models.FloatField()),
                (
                    "operator",
                    models.CharField(
                        choices=[(">", "Greater Than"), ("<", "Less Than")], max_length=4
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="healthcheck.host"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cpu_percentage", models.FloatField()),
                ("ram_percentage", models.FloatField()),
                ("disk_percentage", models.FloatField()),
                ("is_healthy", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="healthcheck.host"
                    ),
                ),
            ],
        ),
    ]
